sudo: false

language: go
go:
  - 1.15.x
  - 1.16.x

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/bradleyfalzon/apicompat/cmd/apicompat
  - go get github.com/fzipp/gocyclo

script:
  - go vet -x ./...
  - test -z "$(golint ./...)"
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - go test -v  ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - test -z "$(apicompat -before ${TRAVIS_COMMIT_RANGE%...*} -after ${TRAVIS_COMMIT_RANGE#*...} ./... | tee /dev/stderr)"

after_script:
  - goveralls -coverprofile=profile.cov -service=travis-ci
  - gocyclo -avg .
